
[workspace]
members = [
  "child-test-daemon/",
  "codegen/",
  "common/",
  "daemon/",
  "parser/",
  "services/apps",
  "services/audiovolumemanager",
  "services/contacts",
  "services/devicecapability",
  "services/geckobridge",
  "services/libsignal",
  "services/powermanager",
  "services/procmanager",
  "services/settings",
  "services/tcpsocket",
  "services/test",
  "services/time",
  "support/android-utils/",
  "support/hidl-utils/",
  "support/libsignal-sys/",
  "support/light/",
  "support/power",
  "support/sqlite-utils",
  "tests/driver",
  "vhost/",
]

[patch.crates-io]
# Bump crossbeam to avoid duplicates
actix = { git = "https://github.com/fabricedesre/actix.git", branch = "0.10-bump-crossbeam" }
# Bump base64 and cookie to avoid duplicates.
webdriver = { path = "support/webdriver" }

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = "abort"
