[package]
name = "audiovolume_service"
version = "0.1.0"
authors = ["Steven Lee <steven.lee@kaiostech.com> "]
edition = "2018"

[dependencies]
common = { path = "../../common" }
log = "0.4"
serde = "1.0"

[build-dependencies]
common = { path = "../../common" }
