[general]
host = "127.0.0.1"
port = 80
message_max_time = 10 # In ms.
verbose_log = false
log_path = "/data/local"
remote_services_config = "/data/local/service/api-daemon/remote_services.toml"
remote_services_path = "/system/api-daemon/remote"
socket_path = "/dev/socket/api-daemon"

[http]
root_path = "/system/api-daemon/http_root"

[vhost]
port = 443
root_path = "/data/local/webapps"
cert_path = "/system/b2g/defaults/local-cert.pem"
key_path = "/system/b2g/defaults/local-key.pem"
csp = "default-src * data: blob:; script-src 'self' http://127.0.0.1 https://shared.local; object-src 'none'; style-src 'self' 'unsafe-inline' https://shared.local"

[apps_service]
root_path = "/system/b2g/webapps"
data_path = "/data/local/webapps"
uds_path = "/data/local/tmp/rust-uds.sock"
cert_type = "production"
