.build_base:
  stage: build
  tags:
    - gecko-dev
  rules:
    - changes:
      - docker/Dockerfile
      when: never
    - if: $CI_COMMIT_MESSAGE =~ /skip-build/
      when: never
    - if: $CI_COMMIT_TAG
      when: never
    - if: '$CI_MERGE_REQUEST_PROJECT_PATH == "KaiOS/sidl"'
  needs: []
