[package]
name = "apps_service"
version = "0.1.0"
authors = ["Seinlin Li<seinlin.li@kaiostech.com> "]
edition = "2018"

[dependencies]
actix-rt = "1.0"
common = { path = "../../common" }
geckobridge = { path = "../geckobridge" }
lazy_static = "1.4"
log = "0.4"
nix = "0.17"
rusqlite = { version = "0.23", features = ["bundled"] }
sanitize-filename = "0.2.1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
sqlite-utils = { path = "../../support/sqlite-utils" }
threadpool = "1.7"
thiserror = "1.0"
zip = { git = "ssh://git@git.kaiostech.com/rust-forks/zip-rs.git", branch="omni-ja", default-features = false, features = ["deflate", "omnija"]}
zip_utils = { git = "ssh://git@git.kaiostech.com/KaiOS/zip_utils.git", branch="master" }
reqwest = { version = "0.10", default-features = false, features = ["blocking", "json", "rustls-tls"] }
assert-json-diff = "1.1.0"
http = "0.2.1"
md-5 = "0.9.1"
hex-slice = "0.1.4"
version-compare = "0.0.10"

[build-dependencies]
common = { path = "../../common" }

[dev-dependencies]
env_logger = "0.7"
